### PR TITLE
Fixed #78: Movie Duration Bug Fixed

### LINKED ISSUE #78: Bug Fixes : List Your Movie component
#### 1. Movie Duration not in proper format 
image
#### 2. Lisiting Duration getting effecting due to Issue 1
image
#### 3. (minor issue) Required Field getting mixed up with the color. I want to upgrade it something noticeable. 
image

I would Like to work on this issues @maniyaom . Please Assign it to me.
Please Add only gssoc-extd tag

### PR DESCRIPTION
**Pull request by Akshithsaai**
### Fixes: #78 
Changed the Movie Duration Format to (HH:MM:SS) and properly validated the input.
### ScreenShot : 
image

### CODE REVIEW

**Comment by maniyaom** [comment]
@Akshithsaai I told you there should not be any limit for the show duration.

image

**Comment by maniyaom** [comment]
don't close this PR. just make commits and push it to your forked repository it will get added.

**Comment by Akshithsaai** [comment]
@maniyaom In the Issue #78 , I did not get any feedback on my idea of limiting show duration So, I assumed You are okay with it. I will change it and update now.

**Comment by Akshithsaai** [comment]
@maniyaom I have removed the Limit for Movie duration. Please check it now

**Comment by maniyaom** [comment]
@Akshithsaai You forgot to change the format where movie duration was used.

image

**Pull request merged**
