### PR TITLE
Removed .env File from Git Tracking

### PR DESCRIPTION
**Pull request by HarshAgrawal1**
This pull request removes the .env file from being tracked by Git to prevent sensitive information from being committed in the future.

**Changes Made:**
Removed the .env file from tracking using git rm --cached .env.
Added .env to .gitignore to ensure it is ignored in future commits.

**Reason:**
The .env file contains sensitive data such as API keys and credentials, which should not be committed to the repository. This change ensures the .env file remains local without being tracked by Git.

**Testing & Verification:**
Verified that .env is now ignored and no longer part of tracked files.

### CODE REVIEW

**Comment by maniyaom** [comment]
@HarshAgrawal1 can you connect me on discord @ommaniya_53106 ?

**Comment by HarshAgrawal1** [comment]
@maniyaom  Yeah sure

**Comment by HarshAgrawal1** [comment]
@maniyaom  Any updates for me? It's fine right

**Comment by maniyaom** [comment]
Please mention related issue in the PR
For example:
Fixes #81 : Removed .env File from Git Tracking

**Pull request merged**
