### PR TITLE
Contact page improved

### PR DESCRIPTION
**Pull request by Mahy-31**

### CODE REVIEW

**Comment by Mahy-31** [comment]
I'm unsure what the problem is when making a pull request here. Can you help me with it, please?

**Comment by Mahy-31** [comment]
Can you review this PR and check if there is any issues?

**Comment by maniyaom** [comment]
@Mahy-31 Please ensure that you verify your solution on your local system before submitting pull requests. Spamming unnecessary PRs could lead to permanent disqualification from contributing to this project.

**Comment by maniyaom** [comment]
@Mahy-31 You've messed up the UI on the login and signup pages.

**Comment by Mahy-31** [comment]
I think the code is working now. Can u check once. And as I have informed earlier, the UI of login and signup was normal. So I made some changes. Kindly check if it's fine.

**Comment by Mahy-31** [comment]
Is the review done sir?

**Comment by maniyaom** [comment]
@Mahy-31 I had pointed out earlier that there were some issues with the UI layout. You have not made any changes to that.

**Comment by Mahy-31** [comment]
> @Mahy-31 I had pointed out earlier that there were some issues with the UI layout. You have not made any changes to that.

To which page sir? This task was all about contact page sir. If there are anymore changes to be done, kindly let me know sir.

**Comment by maniyaom** [comment]
@Mahy-31 Login and Sign Up page.

**Comment by Mahy-31** [comment]
> @Mahy-31 Login and Sign Up page.

@maniyaom  Then should I remove the background of the login and signup and give a pull request again?

**Pull request closed without merging**
