### PR TITLE
Resolved the issue of the previous PR of feedback section.

### PR DESCRIPTION
**Pull request by shriyadindi**
issue no. : #356 
I've resolve the issue of the previous PR of feedback section. #363 
Screenshot 2024-10-20 025230

### CODE REVIEW

**Comment by Khizarshah01** [comment]
@shriyadindi can you change the color according to the theme of the website?

**Comment by shriyadindi** [comment]
@Khizarshah01 okay!

**Comment by shriyadindi** [comment]
@Khizarshah01 Changed the theme, do check it!

**Review by Khizarshah01 — APPROVED** [review]
Done!

**Comment by shriyadindi** [comment]
@Khizarshah01 please add gssoc and hacktoberfest and level badge

**Pull request merged**
