### PR TITLE
Updated UI for Easier Addition of Movies

### PR DESCRIPTION
**Pull request by Akshithsaai**

### CODE REVIEW

**Comment by maniyaom** [comment]
@Akshithsaai ,you messed up the login and signup pages. Please fix it

**Comment by Akshithsaai** [comment]
@maniyaom I have reviewed your comment and updated the code. Its Working Good now

### ScreenShots : 
#### Login Page:
image
#### Signup page:
image
#### List Movie page:
image

**Comment by maniyaom** [comment]
@Akshithsaai ,In this image, you can see that when viewed on a mobile device, five fields are aligned on the right and five on the left. If the user is opening this on a mobile device, there should not be two separate sections.
image

**Comment by Akshithsaai** [comment]
#15 
@maniyaom  I have worked on this bug and fixed it. Please check and merge this PR.
The changes on done only on List movie page and no where else affected. 

### Screenshots: 
#### Laptop View:
image
##### Mobile View:
image

**Comment by maniyaom** [comment]
@Akshithsaai Whenever you raise a pull request, please ensure you mention the related issue number in the PR description. This will help me navigate to the issue easily and close it.

For example:
Fix #15 
Updated UI for Easier Addition of Movies

**Comment by Akshithsaai** [comment]
@maniyaom Thank you for the info. I will definitely follow your Suggestion in the next PR.

**Comment by Akshithsaai** [comment]
@maniyaom 
PR #43  made changes that effected the styling of List your movie page.

I request you to look back onto this.

**Comment by maniyaom** [comment]
@Akshithsaai Okay, I will look into it.

**Pull request merged**
