### PR TITLE
ContactUs Form added and UI enhanced

### LINKED ISSUE #221: [Feat]: ContactUS Form
### Feature Description

A form can be added in the page to let user input their msgs and reach to you in a click from your website only

### Provide a detailed description of the feature

I would like to add a form in the Contact Us page with fields:
Name, email, Their Msg and a send button 

And also on the other hand, would add your contact details in more aligned way.

Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.

### Put here any screenshots or videos (optional)

_No response_

### By submitting this issue, you agree to

- [X] I agree to follow this project's Code of Conduct
- [X] I’ve read all the issues in the issue section, and this feature has not been proposed yet.

### Other Information

- [X] I'm a GSSoC '24 Extended contributor
- [X] I'm a Hacktoberfest '24 contributor
- [X] I am willing to work on this feature (optional)

### PR DESCRIPTION
**Pull request by Bhum-ika**
image
Fixed #221 

Kindly **add the required tags while merging too** and attach the **level badge** too. **_I would really appreciate if you could add level2 or level3 badge in the PR._**
Thank you

### CODE REVIEW

**Comment by Bhum-ika** [comment]
@maniyaom Please have a look

**Comment by maniyaom** [comment]
@Bhum-ika Contact Us page has become unresponsive.

**Comment by Bhum-ika** [comment]
Can i raise another issue for this or should I fix in this only?

**Comment by maniyaom** [comment]
@Bhum-ika you have not used this contact form details.

**Comment by Bhum-ika** [comment]
If you are talking about functionality, i can implement email.js for that, it will work easily, but for that I should be needing credentials of an account

**Comment by maniyaom** [comment]
@Bhum-ika please create a temporary account. After completing the task, I will change it to my account's credentials.

**Comment by Bhum-ika** [comment]
Okay

**Comment by maniyaom** [comment]
@Bhum-ika and don't raise another PR. just do commits and push it, that will be added to this PR.

**Comment by Bhum-ika** [comment]
okay

**Comment by Bhum-ika** [comment]
@maniyaom Please check

Screenshot 2024-10-12 233552
Screenshot 2024-10-12 233559

**I would really appreciate it if you could attach _level 3_ to my PR. Also, please add other badges such as gssoc-ext and hacktoberfest-accepted. I have made it responsive and fully functional.**

**Review by maniyaom — APPROVED** [review]

**Pull request merged**
