### PR TITLE
Added Offer Section(#53)

### LINKED ISSUE #53: Add 'Offers' Section to Navigation Bar, To increase the User Engagement.
#### Description:
We need to add an **' Offers' section** to the navigation bar of the movie booking ticket website to highlight current promotions and discounts for users.

#### Why is this important?
- This section will attract users to take advantage of ongoing offers, increasing engagement and ticket sales.
- It will provide a dedicated space for users to easily find promotions and special deals.

#### Comment:
- The 'Offers' section should be clearly visible in the navigation bar.
- It should link to a dedicated page listing all current offers, including terms and conditions.
- Ensure the design is consistent with the existing navigation style and easy to access.

Example:
image

### PR DESCRIPTION
**Pull request by SCR01**
# Title: Add 'Offers' Section to Navigation Bar

## Related Issue
Closes #53

## Description
This pull request implements an 'Offers' section in the navigation bar of the movie booking ticket website. The new section highlights current promotions and discounts available to users.

### Changes Made
- Added 'Offers' section to the navigation bar.
- Created a dedicated page that lists all current offers, including terms and conditions.
- Ensured that the design is consistent with the existing navigation style for a seamless user experience.

## Screenshots
Screenshot 2024-10-08 055752

Video:

https://github.com/user-attachments/assets/fa6c0683-fcaa-45d0-935d-c72f7aab4da2

## Checklist
- [x] I have performed a self-review of my code.
- [x] I have followed the contribution guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional Context
This addition is important as it attracts users to take advantage of ongoing offers, thereby increasing engagement and ticket sales. The 'Offers' section will provide a dedicated space for users to easily find promotions and special deals, enhancing their overall experience on the platform.

### CODE REVIEW

**Comment by maniyaom** [comment]
@SCR01 I haven't assigned this issue to you yet, so please refrain from starting work on any issue until it has been assigned.

The page you created is just a static page, which doesn't make much sense. If you have any suggestions or if I'm misunderstanding something, please feel free to explain further.

**Comment by SCR01** [comment]
@maniyaom You assigned me that's why I am working on it.  The page is static because site all the pages are static I even added the filter offer part, also the offer section definitely helps the user to spend according to their suitable way.

**Comment by maniyaom** [comment]
> @maniyaom You assigned me that's why I am working on it. The page is static because site all the pages are static I even added the filter offer part, also the offer section definitely helps the user to spend according to their suitable way.

Sorry for the confusion, but even if we add this page, there’s currently no way for users to use these offers, as that functionality hasn't been implemented yet.

**Comment by maniyaom** [comment]
@SCR01 also you just added offers in offers.js, but that's not the best approach for implementing this feature. You should design it so that the admin can add offers, which will be stored in the database and displayed to all users

**Comment by SCR01** [comment]
@maniyaom The reason I created this issue Because we usually see the offer section in the ticket booking site, now if I add a database in it and also need to do some system design we can definitely allow the admin to add offers but this will affect the file structure badly.

**Comment by maniyaom** [comment]
@SCR01 If admin can't add or update offers then this page will be useless.

**Comment by SCR01** [comment]
@maniyaom So it's fine, Do as you please.

**Pull request closed without merging**
