### PR TITLE
Fixed some issues

### PR DESCRIPTION
**Pull request by Avidiptab17**
Issue no (#260)

### CODE REVIEW

**Comment by maniyaom** [comment]
@Avidiptab17 Please mention your issue number in this PR.

**Comment by Avidiptab17** [comment]
> 

#260

**Comment by maniyaom** [comment]
@Avidiptab17 I don't see any major changes. You mentioned that you would add a logo and improve responsiveness. While a logo might not be necessary, it seems you haven't worked on the responsiveness either.

**Comment by Avidiptab17** [comment]
No, I changed the color grading in index.css file of the scrollbar, but no option was available for that issue number so, I found that nearest so, I raised issue no 260.

**Comment by maniyaom** [comment]
@Avidiptab17 You need to address the issue assigned to you. Simply changing the scrollbar color is not considered a valid contribution, which is why I am closing this PR.

**Pull request closed without merging**
