### PR TITLE
Adding a filter for genre of movies in Home page

### LINKED ISSUE #54: A filter for the genre of the movie can be added like action, horror for search
Description: A filter for the genre can be added like action, horror for search

image

image
like this 

The posters are fetched from firebase . A column for genre can be added.

### PR DESCRIPTION
**Pull request by Nikitaganeshbabu**
FIXED #54   Adding filter for genre of movie

Here is the description of  the filter 
The filter is for    - [All , Horror , Action , Adventures , Drama]
I have made changes in Home.js and Home.css
Iam a contributor in gssoc and Hoctoberfest
image

If my PR accepted , Kindly assign me the label for the level of issue

### CODE REVIEW

**Comment by maniyaom** [comment]
@Nikitaganeshbabu Please specify your issue number while raising PR.
just edit comment in this PR.

for example:
fixed #<replace_with_issue_number> Added a filter for genre of movies in Home page

**Comment by Nikitaganeshbabu** [comment]
this is my first ever contribution . Iam not aware of this .I didn't make any changes . Should I make a new PR or you can remove it from pushing ?

**Comment by Nikitaganeshbabu** [comment]
I made changes only in Home.js and Home.css

**Comment by maniyaom** [comment]
@Nikitaganeshbabu Okay, I will fix it no need to raise new PR.

**Comment by Nikitaganeshbabu** [comment]
Kindly review my code

**Comment by maniyaom** [comment]
@Nikitaganeshbabu You messed with some functionalities of the code which was previously contributed by others. It takes time to fix that.

**Review by maniyaom — APPROVED** [review]

**Pull request merged**
