### PR TITLE
Table of Contents, Initial Setup and Prerequisites

### PR DESCRIPTION
**Pull request by Rx-Metallica**
#117 #137 
Added Table of Contents :-
Introduction, Features, Installation, Usage, Code of conduct, Contributing and Guidelines.

Please check and edit for any new changes😊

### CODE REVIEW

**Comment by maniyaom** [comment]
@Rx-Metallica DM me here https://www.linkedin.com/in/om-maniya-896222269

**Comment by Rx-Metallica** [comment]
> @Rx-Metallica DM me here https://www.linkedin.com/in/om-maniya-896222269

Can u pls i am not able to https://www.linkedin.com/in/aditya-mote-610367259?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app

**Comment by maniyaom** [comment]
@Rx-Metallica are you on discord? ommaniya_53106

**Comment by Rx-Metallica** [comment]
> @Rx-Metallica are you on discord? ommaniya_53106

Messaged you on linkedin pls check

**Pull request closed without merging**
