### PR TITLE
Implemented 404 Error Page

### PR DESCRIPTION
**Pull request by Hemant9808**
Pull Request: Implement 404 Error Page , issue #263 
Summary:
This pull request adds a custom 404 error page to the application to handle cases where users navigate to non-existent routes. The page provides a user-friendly message and a button to redirect users back to the homepage. It is fully responsive, using Tailwind CSS for styling, and adjusts the layout based on screen size.

Responsive Layout:

- Used flex md:flex-row flex-col for responsiveness to adjust the layout between mobile and desktop views.

- Adjusts between column layout on smaller screens and row layout on larger screens.
  Styling:

Screenshot 2024-10-13 004630

### CODE REVIEW

**Comment by Hemant9808** [comment]
fixes #263 
i have added the 404 page
Screenshot 2024-10-13 004630

Kindly merge this pull requrest @maniyaom

**Comment by Hemant9808** [comment]
sorry i forgot to remove my firebase credentials, please replace then with yours in firebase.js file
Screenshot 2024-10-13 010640

**Comment by maniyaom** [comment]
@Hemant9808 Looks like page is not responsive for all the devices.

**Comment by Hemant9808** [comment]
> @Hemant9808 Looks like page is not responsive for all the devices.

okh Let check

**Pull request closed without merging**
