### PR TITLE
Responsiveness Added

### PR DESCRIPTION
**Pull request by SatyaJaiss**
I've made the responsive, now it works better on smaller screen devices

### CODE REVIEW

**Comment by maniyaom** [comment]
@SatyaJaiss there are some conflicting files please fix that.

**Comment by SatyaJaiss** [comment]
@maniyaom kindly review

**Comment by maniyaom** [comment]
@SatyaJaiss sorry, I can't merge this PR because another contributor recently added the toggle password functionality, and you removed it. If you can fix that, I will definitely merge your PR.

**Comment by SatyaJaiss** [comment]
@maniyaom okay I will fix that shortly.

**Comment by maniyaom** [comment]
@SatyaJaiss Whenever you raise a pull request, please ensure you mention the related issue number in the PR description. This will help me navigate to the issue easily and close it.

For example:
Fix #3 
I've made the responsive, now it works better on smaller screen devices

**Pull request merged**
