### PR TITLE
Added the feature of My Tickets

### PR DESCRIPTION
**Pull request by rishabhrawat05**
Hi @maniyaom 
**The project has been updated** 
Here, is the screenshot
Screenshot (194)

Also to mention that **My Tickets** option in navbar will only showup once the user is logged in to the account

### CODE REVIEW

**Comment by maniyaom** [comment]
@rishabhrawat05 subtotal is displayed in '$'. Replace it to '₹'.

**Comment by rishabhrawat05** [comment]
> @rishabhrawat05 subtotal is displayed in '$'. Replace it to '₹'.

Updated '$' to '₹'

**Comment by maniyaom** [comment]
@rishabhrawat05 Whenever you raise a pull request, please ensure you mention the related issue number in the PR description. This will help me navigate to the issue easily and close it.

For example:
Fix #4 
Added the feature of My Tickets

**Comment by rishabhrawat05** [comment]
> @rishabhrawat05 Whenever you raise a pull request, please ensure you mention the related issue number in the PR description. This will help me navigate to the issue easily and close it.
> 
> For example: Fix #4 Added the feature of My Tickets

Okay, thank you 😊

**Pull request merged**
