### PR TITLE
fix overflow of textarea 

### PR DESCRIPTION
**Pull request by shivamy009**
### I have added styling for textarea so that it can't overflow.

#9 I have added max width to textarea.

### CODE REVIEW

**Comment by maniyaom** [comment]
@shivamy009 , the textarea's overflow issue is fixed now, but you also changed the navbar's CSS. Please fix it.

It used to look like this:
image

But now it looks like this after your modification:
image

**Comment by shivamy009** [comment]
> @shivamy009 , the textarea's overflow issue is fixed now, but you also changed the navbar's CSS. Please fix it.
> 
> It used to look like this: image
> 
> But now it looks like this after your modification: image

**Comment by shivamy009** [comment]
> > @shivamy009 , the textarea's overflow issue is fixed now, but you also changed the navbar's CSS. Please fix it.
> > It used to look like this: image
> > But now it looks like this after your modification: image
 
you want white text?

**Comment by maniyaom** [comment]
@shivamy009 Yes, it should be white and bold as it was before.

**Comment by maniyaom** [comment]
@shivamy009 I cannot see any fix to this. Before raising pull request make sure it is fixed completely.
image

**Comment by shivamy009** [comment]
> @shivamy009 I cannot see any fix to this. Before raising pull request make sure it is fixed completely. image

please checkout now

**Comment by maniyaom** [comment]
@shivamy009 Perfect

**Pull request merged**
