### PR TITLE
Google sign in with some warning changes

### PR DESCRIPTION
**Pull request by akankshagoel28**
Firstly I have added the google button on the sign in page, i also made some changes in the naming to get a clear idea and made some changes for I was getting a lot of warnings on my terminal, there are still a lot of warnings, if you want i will create a new issue for that

### CODE REVIEW

**Comment by maniyaom** [comment]
@akankshagoel28 Why you have modified other pages also? You just have to work on your assigned task only.

Raise new PR and modify only assigned page (Login page).

Note: Work on latest repository

**Comment by akankshagoel28** [comment]
there were a lot of warnings when i ran the repo that is why, i changed the name since i thought it would be easier to understand

**Comment by maniyaom** [comment]
@akankshagoel28 why you modified these files?

Ignore the warnings and modify just login and signup page. You can modify signup page only if it is required.

also, Do you also want to work on Forgot Password issue?

**Comment by akankshagoel28** [comment]
alright i will work on those issues and modify only the login page with the forgot password feature

**Pull request closed without merging**
