### PR TITLE
Implement Making Search movie feature #84

### PR DESCRIPTION
**Pull request by anuragbansall**
This pull request addresses **issue #84**  by introducing the search movies feature, allowing users to find movies by title efficiently. Previously, users could only browse movies without a dedicated search functionality, making it difficult to locate specific titles.

**Changes made:**

Screenshot 2024-10-05 122347

- Implemented a responsive search bar in the UI for seamless user interaction.
- Dynamic rendering of search results, providing users with instant feedback on their queries.
- Included error handling to manage scenarios where no results are found or if the API fails.
- This feature enhances the overall user experience by facilitating quick and easy movie searches, making the application more user-friendly.

### CODE REVIEW

**Comment by anuragbansall** [comment]
Hey @maniyaom please authorize it!

**Comment by maniyaom** [comment]
@anuragbansall size of the search results is very big no need to include images in that.
Example:

image

**Review by anuragbansall — COMMENTED** [review]
Hi @maniyaom ,

I've made the requested changes. Please review them when you have a moment!

Thank you!

**Review by anuragbansall — COMMENTED** [review]
Screenshot 2024-10-05 173206

**Comment by maniyaom** [comment]
@anuragbansall still this is big. Please make it smaller and remove the video icon you placed before the title.

**Review by anuragbansall — COMMENTED** [review]
Hi @maniyaom , I’ve made all the requested changes. Please review and consider my PR now.

Screenshot 2024-10-06 115900

**Pull request merged**
