### PR TITLE
Fixes #228  Validation and Timings updated for listing a Movie 

### LINKED ISSUE #228: [Feat]: Form Validation and Adding a default time for Listing movies
### Feature Description

Form Validation and Default Time for Movie Shows

### Issues:
While Listing movie a Movie on Ticketify, The Form is not validated for most of the fields. 
example : Movie Language should not be a number, Ticket Price should not be a string. 
I have created a test movie with the ticket price as a string it shows insufficient Balance even though there is some balance in my account.

Also I propose to add a default movie Time Feature. 

### Solution
1. To implement form validation in listing the movies.
2. Changes to Movie Timings as shown below.

Please check screenshots.

### Current version: 
image
image
image

image

### Proposed Version
Validated Form  and 
image

### By submitting this issue, you agree to

- [X] I agree to follow this project's Code of Conduct
- [X] I’ve read all the issues in the issue section, and this feature has not been proposed yet.

### Other Information

- [X] I'm a GSSoC '24 Extended contributor
- [X] I'm a Hacktoberfest '24 contributor
- [X] I am willing to work on this feature (optional)

### PR DESCRIPTION
**Pull request by Akshithsaai**
Fixes: #228 

Implemented Required validation for listing movie and also added default timing values to movie timings.
### ScreenShots:

image

@maniyaom Please check it out.

### CODE REVIEW

**Comment by Akshithsaai** [comment]
@maniyaom Please check the validation and suggest the changes...

**Comment by maniyaom** [comment]
@Akshithsaai Sorry for the delayed response, I’ve been tied up the past two days.

**Comment by maniyaom** [comment]
@Akshithsaai If the user does not add a poster, they are still able to add the movie.

**Comment by Akshithsaai** [comment]
@maniyaom I will add the validation and update the PR by today EOD.

**Comment by Akshithsaai** [comment]
@maniyaom  I have added validation , Please check.

image
image

**Pull request merged**
