### PR TITLE
feat : Responsive footer for various screen sizes

### PR DESCRIPTION
**Pull request by laxmanp090404**
I have implemented responsive footer as assigned in the issue #22  for me for gssoc ext and hacktober fest.
Please find the below demo  of implementation

**Desktop:**
image

**Tablet:**
image

**Mobile:**
image

### CODE REVIEW

**Comment by laxmanp090404** [comment]
@maniyaom  Please assign me level label also sir.

**Comment by maniyaom** [comment]
@laxmanp090404 , everything is perfect, but please center the 'About Us' title in the footer when viewed on mobile.

**Comment by laxmanp090404** [comment]
Ok  @maniyaom  will do it sir.

**Comment by laxmanp090404** [comment]
As assigned I have **resolved the footer mobile view** issue . Please provide me **level1, level2 or level3 label** and **merge** my PR. 
Thanks.
image

**Pull request merged**
