### PR TITLE
Added verification field and email

### PR DESCRIPTION
**Pull request by tanish35**

### CODE REVIEW

**Comment by tanish35** [comment]
Added Verification which is to be sent after signup

Pls add hacktoberfest-accepted and also hacktoberfest tag on this pr

**Comment by maniyaom** [comment]
@tanish35 I am not receiving any verification email during the signup process. Maybe you forgot to update the URL to the deployed website.
image

**Comment by tanish35** [comment]
ok let me provide a ss and also provide the email credentials

**Comment by tanish35** [comment]
image
Hi yeah so the mail arrives

The reason why its not arriving in yours is because  had refreshed the credentials

You may go to mailjs and create a account by linking your gmail. Or if you can provide a gmail account to me then i can hardcode the credentials for you

**Comment by maniyaom** [comment]
@tanish35 as a user, the email should arrive directly in my Gmail inbox without requiring registration on any third-party application.

**Comment by tanish35** [comment]
The email will arrive in your mailbox only. I am saying that you need to register for the mail sending api key

Pls provide me with a gmail account so i can hardcode the credentials

**Comment by maniyaom** [comment]
> @maniyaom The email will arrive in your mailbox only. I am saying that you need to register for the mail sending api key
> 
> Pls provide me with a gmail account so i can hardcode the credentials

Firebase is providing service for email verification. You can use that instead of using any third-party services.

**Comment by tanish35** [comment]
image

I am unable to check the deployment. Please do check it should be working now

**Comment by maniyaom** [comment]
@tanish35 In chrome developer console I can see this failure.

image

**Comment by tanish35** [comment]
Pls do verify the deployment now

**Comment by maniyaom** [comment]
@tanish35 I cannot see any progress. Please let me know if you can fix this issue or not? If you can't then I have to close this PR.

**Comment by tanish35** [comment]
image

The new commit hasn't been deployed. If you want i can provide ss or video of it working
@maniyaom

**Comment by maniyaom** [comment]
@tanish35 provide the screenshot.

**Comment by tanish35** [comment]
image

@maniyaom

**Comment by maniyaom** [comment]
@tanish35 I believe there's some confusion. What I'm trying to explain is that Firebase offers a built-in service for email verification. When a user logs in, Firebase generates an authorization token, which includes a field indicating whether the email is verified or not.

Additionally, since we're already using Firebase Authentication for both Sign Up and Sign In, it makes sense to continue using Firebase instead of integrating any other third-party service.

**Pull request closed without merging**
